# Generated by Django 4.0.3 on 2022-04-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicamentos',
            new_name='ListMedicamentos',
        ),
    ]
