# Generated by Django 4.0.3 on 2022-04-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_medicamentos_listmedicamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDeEvolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('carrera', models.CharField(max_length=100)),
                ('grupo', models.IntegerField()),
                ('matricula', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('padecimiento_actual', models.CharField(max_length=100)),
                ('alegias', models.CharField(max_length=2)),
                ('cuales_alegias', models.CharField(max_length=100)),
                ('exploracion_fisica', models.CharField(max_length=100)),
                ('otro', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('referencias', models.CharField(max_length=2)),
                ('Institución', models.CharField(max_length=2)),
            ],
        ),
    ]
